services:
  my_broker:
    image: rabbitmq:3-management
    container_name: my_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
     - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_data: 